name: full_example
description: An example project that demonstrates all Widgetbook features.
publish_to: none
version: 1.0.0+1

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=3.27.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^2.4.4
  widgetbook_generator:
    path: ../../packages/widgetbook_generator

dependency_overrides:
  widgetbook:
    path: ../../packages/widgetbook
  widgetbook_annotation:
    path: ../../packages/widgetbook_annotation

flutter:
  uses-material-design: true
