name: widgetbook_generator
description: A package to automate setup and maintenance of the widgetbook package by using code generation.
version: 3.13.0
homepage: https://www.widgetbook.io?utm_source=pub.dev&utm_medium=link&utm_campaign=widgetbook_generator
repository: https://github.com/widgetbook/widgetbook/tree/main/packages/widgetbook_generator
issue_tracker: https://github.com/widgetbook/widgetbook/issues
documentation: https://docs.widgetbook.io
topics: [widgetbook, storybook, ui, codegen, build-runner]
publish_to: none

screenshots:
  - description: Widgetbook Logo
    path: assets/logo.png

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  analyzer: ">=6.5.0 <8.0.0"
  build: 3.1.0
  code_builder: ^4.5.0
  collection: ^1.15.0
  crypto: ^3.0.0
  glob: ^2.0.2
  meta: ^1.7.0
  path: ^1.8.0
  source_gen: 3.0.0
  widgetbook_annotation:
    path: ../../packages/widgetbook_annotation

dev_dependencies:
  dart_style: 3.0.0
  test: ^1.21.0
